version: "3"

services:
  postgresdb:
    image: "postgres:12.0"
    container_name: learner-db
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=learner
    expose:
      - "5432"
    ports:
      - 5440:5432

